CREATE TABLE IF NOT EXISTS tcg_card (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255),
    name_pl VARCHAR(255),
    supertype VARCHAR(64),
    subtypes VARCHAR(255),
    stage VARCHAR(32),
    hp INT,
    type VARCHAR(32),
    pokedex_number INT,
    set_id VARCHAR(32),
    rarity VARCHAR(64),
    image_url_small VARCHAR(512),
    image_url_large VARCHAR(512),
    flavor_text VARCHAR(1000),
    flavor_text_pl VARCHAR(1000),
    weakness VARCHAR(64),
    resistance VARCHAR(64),
    retreat INT,
    overall_rating INT,
    cardmarket_url VARCHAR(512),
    cardmarket_avg_sell_price DOUBLE,
    cardmarket_low_price DOUBLE,
    CONSTRAINT fk_set_id FOREIGN KEY (set_id) REFERENCES card_set(id)
    );